networks:
  ai-engineering-basics:
    driver: bridge

services:
  # api:
  #   container_name: ai-engineering-basics-api
  #   build: .
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./src:/app/src
  #   ports:
  #     - "${PORT}:${PORT}"
  #   networks:
  #     - ai-engineering-basics
  chromadb:
    container_name: ai-engineering-basics-chromadb
    image: chromadb/chroma:1.0.0b0
    ports:
      - "8000:8000"
    volumes:
      - ./chroma:/chroma
    networks:
      - ai-engineering-basics
    environment:
      - PERSIST_DIRECTORY="/chroma"

