services:
  # api:
  #   container_name: ai-engineering-basics-api
  #   build: .
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./src:/app/src
  #   ports:
  #     - "${PORT}:${PORT}"
  #   networks:
  #     - ai-engineering-basics
  chromadb:
    container_name: ai-engineering-basics-chromadb
    image: chromadb/chroma:0.6.4.dev266
    ports:
      - "8000:8000"
    volumes:
      - ./chroma:/chroma
    networks:
      - ai-engineering-basics
    environment:
      - CHROMA_DB_IMPL=duckdb  # Use DuckDB for persistence
      - CHROMA_PERSIST_DIRECTORY=/chroma  # Store data in /chroma

networks:
  ai-engineering-basics:
    driver: bridge

